[package]
name = "nto-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.8.17", features = ["csr"] }
wasm-bindgen = "0.2.117"
wasm-bindgen-futures = "0.4.67"
js-sys = "0.3.94"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6.5"
console_error_panic_hook = "0.1.7"
leptos_router = { version = "0.8.13" }
env_logger = "0.11.10"
log = "0.4"
gloo-timers = { version = "0.4.0", features = ["futures"] }

[workspace]
members = ["src-tauri"]
